import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Home from "@/components/Menu";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/remixicon/4.6.0/remixicon.css" />
        <style>
          {`
            body {
              -ms-overflow-style: none; 
              scrollbar-width: none;
            }
            body::-webkit-scrollbar {
              display: none;
            }
            .scrollbar-hide::-webkit-scrollbar {
              display: none;
            }
            .scrollbar-hide {
              -ms-overflow-style: none; /* IE and Edge */
              scrollbar-width: none; /* Firefox */
            }
          `}
        </style>
      </head>
      <body
        className={`${montserrat.variable} ${montserrat.variable} antialiased min-h-screen ` } 
      >

        {children}
        <Home />
      </body>
    </html>
  );
}
